# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to=b'')),
                ('abilities', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='comics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comics'),
        ),
    ]
